# Generated by Django 4.1.3 on 2022-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hora_extra', '0003_horaextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='utilizado',
            field=models.BooleanField(default=False),
        ),
    ]
